---
- name: check if EPEL repo is already configured
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: install nagios client packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - nrpe
    - nagios-plugins-all
    - nagios-plugins*

- name: start and enable nrpe
  service:
    name: nrpe
    enabled: true
    state: started

- name: deploy nrpe.cfg
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart nrpe
